// <auto-generated />
using System;
using GardenCommunityAccounting;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GardenCommunityAccounting.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GardenCommunityAccounting.Models.DocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOutcome")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64501dc6-695c-4f29-ab13-5481a529c228"),
                            IsIncome = true,
                            IsOutcome = false,
                            Name = "Електроенергія"
                        },
                        new
                        {
                            Id = new Guid("6ac1c44f-2db3-4a54-9bd7-fc3dc40bcdb1"),
                            IsIncome = true,
                            IsOutcome = false,
                            Name = "Податок на землю"
                        },
                        new
                        {
                            Id = new Guid("0f4400dd-dd58-405d-ae7e-34fd0693bd15"),
                            IsIncome = true,
                            IsOutcome = false,
                            Name = "Цільовий внесок"
                        });
                });

            modelBuilder.Entity("GardenCommunityAccounting.Models.Land", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Lands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ccff0ea0-050b-4dd6-a888-b9af88e2284c"),
                            IsPrivate = false,
                            Number = 0
                        },
                        new
                        {
                            Id = new Guid("2d5eccfe-b081-455e-8cf5-25808d1b4923"),
                            IsPrivate = false,
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("fd413b70-1a3e-45e1-aab8-0fa57819a901"),
                            IsPrivate = false,
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("9942a636-00c2-4f2c-86c3-5472f1b76e8b"),
                            IsPrivate = false,
                            Number = 3
                        },
                        new
                        {
                            Id = new Guid("9e4516bb-32eb-4265-a9f0-be80cdb1f99c"),
                            IsPrivate = false,
                            Number = 4
                        },
                        new
                        {
                            Id = new Guid("c824afdf-96b4-44a1-b659-8774e3a567c8"),
                            IsPrivate = false,
                            Number = 5
                        },
                        new
                        {
                            Id = new Guid("a65601b8-8d23-42bb-a748-a8bbba19d691"),
                            IsPrivate = false,
                            Number = 6
                        },
                        new
                        {
                            Id = new Guid("12278c92-643d-4ffd-82ab-527c237e55d1"),
                            IsPrivate = false,
                            Number = 7
                        },
                        new
                        {
                            Id = new Guid("90838013-956f-44f5-80e5-eeafe0339703"),
                            IsPrivate = false,
                            Number = 8
                        },
                        new
                        {
                            Id = new Guid("6ec6f7a3-61e2-480d-a043-7e4e4d8c408b"),
                            IsPrivate = false,
                            Number = 9
                        },
                        new
                        {
                            Id = new Guid("20013837-17e3-43eb-904f-d57908f3f007"),
                            IsPrivate = false,
                            Number = 10
                        },
                        new
                        {
                            Id = new Guid("7620b32b-52c9-4c02-a0ed-b0b8a20f863b"),
                            IsPrivate = false,
                            Number = 11
                        },
                        new
                        {
                            Id = new Guid("aeba710c-5e2a-4d0a-ac1b-8cc699e76cbb"),
                            IsPrivate = false,
                            Number = 12
                        },
                        new
                        {
                            Id = new Guid("a4d67c9e-cd24-4e4d-a400-dd296ce9c439"),
                            IsPrivate = false,
                            Number = 13
                        },
                        new
                        {
                            Id = new Guid("0b306745-b814-43a9-98f0-cea16aae530a"),
                            IsPrivate = false,
                            Number = 14
                        },
                        new
                        {
                            Id = new Guid("5e4c7ec9-52a5-4e9c-8b00-f110ddaadb6e"),
                            IsPrivate = false,
                            Number = 15
                        },
                        new
                        {
                            Id = new Guid("1d46813c-de24-4ee5-908a-2c5b9427a995"),
                            IsPrivate = false,
                            Number = 16
                        },
                        new
                        {
                            Id = new Guid("5c18bfaa-d06e-4b51-87f9-3fbeb6c6eada"),
                            IsPrivate = false,
                            Number = 17
                        },
                        new
                        {
                            Id = new Guid("7c631882-4127-4336-9959-d97557ca977a"),
                            IsPrivate = false,
                            Number = 18
                        },
                        new
                        {
                            Id = new Guid("f3c20bb3-9885-47aa-8ed3-0b8e0e589657"),
                            IsPrivate = false,
                            Number = 19
                        },
                        new
                        {
                            Id = new Guid("25bb7663-be2c-49b9-9897-1bef857922ee"),
                            IsPrivate = false,
                            Number = 20
                        },
                        new
                        {
                            Id = new Guid("e10825be-330a-4d41-abe0-ec1cb955af20"),
                            IsPrivate = false,
                            Number = 21
                        },
                        new
                        {
                            Id = new Guid("f36afd48-9bfe-4dc2-a67a-1e2584580eb0"),
                            IsPrivate = false,
                            Number = 22
                        },
                        new
                        {
                            Id = new Guid("c27bc2b7-9aa8-4614-b906-1b1cd276da8c"),
                            IsPrivate = false,
                            Number = 23
                        },
                        new
                        {
                            Id = new Guid("0ac147e1-8707-4041-8176-83dd4703383a"),
                            IsPrivate = false,
                            Number = 24
                        },
                        new
                        {
                            Id = new Guid("03fd0641-3a1d-4c7b-b6b0-92d0ce67fd24"),
                            IsPrivate = false,
                            Number = 25
                        },
                        new
                        {
                            Id = new Guid("08e5a86f-5ada-4b89-a655-c38fa582c738"),
                            IsPrivate = false,
                            Number = 26
                        },
                        new
                        {
                            Id = new Guid("5133180b-178b-4c84-bef7-5425d78de1e1"),
                            IsPrivate = false,
                            Number = 27
                        },
                        new
                        {
                            Id = new Guid("3ace260f-db00-4258-a17e-6124f6db43ef"),
                            IsPrivate = false,
                            Number = 28
                        },
                        new
                        {
                            Id = new Guid("3facc545-2d86-4de8-a9c4-6ea3a0363f6f"),
                            IsPrivate = false,
                            Number = 29
                        },
                        new
                        {
                            Id = new Guid("3d855327-3a8c-4846-ab1f-6e70e2980eec"),
                            IsPrivate = false,
                            Number = 30
                        },
                        new
                        {
                            Id = new Guid("a9c8edc1-11b3-4f0e-aba0-98f6f1819778"),
                            IsPrivate = false,
                            Number = 31
                        },
                        new
                        {
                            Id = new Guid("7c086bd0-a834-48ce-bbc2-cc55bc83c431"),
                            IsPrivate = false,
                            Number = 32
                        },
                        new
                        {
                            Id = new Guid("dc2a743a-7266-4882-9326-8cd80313468a"),
                            IsPrivate = false,
                            Number = 33
                        },
                        new
                        {
                            Id = new Guid("9ec17bf9-3ace-44d2-b7ad-204dd7254d68"),
                            IsPrivate = false,
                            Number = 34
                        },
                        new
                        {
                            Id = new Guid("ee0764e1-cd7e-4495-a5b8-fd895817fd82"),
                            IsPrivate = false,
                            Number = 35
                        },
                        new
                        {
                            Id = new Guid("5bb3cada-d833-4f34-9185-72ae098a67df"),
                            IsPrivate = false,
                            Number = 36
                        },
                        new
                        {
                            Id = new Guid("9baf5cdf-ce13-4a00-9c9f-0d006d92bf18"),
                            IsPrivate = false,
                            Number = 37
                        },
                        new
                        {
                            Id = new Guid("2ef60b94-b302-427d-9724-e994c5f1d120"),
                            IsPrivate = false,
                            Number = 38
                        },
                        new
                        {
                            Id = new Guid("783dfda8-5e6d-40e1-971b-dda198247a95"),
                            IsPrivate = false,
                            Number = 39
                        },
                        new
                        {
                            Id = new Guid("ee634f04-3d6a-465d-a3e8-a5347757d9bb"),
                            IsPrivate = false,
                            Number = 40
                        },
                        new
                        {
                            Id = new Guid("143f675e-93b3-4c4c-9d14-0afdd60f24ff"),
                            IsPrivate = false,
                            Number = 41
                        },
                        new
                        {
                            Id = new Guid("de4c3792-b3be-4396-8f32-2487a7bd2281"),
                            IsPrivate = false,
                            Number = 42
                        },
                        new
                        {
                            Id = new Guid("66be0796-4c1d-4a0f-9806-862b1925d883"),
                            IsPrivate = false,
                            Number = 43
                        },
                        new
                        {
                            Id = new Guid("b09fd388-5686-4bbc-b9ef-8f47dfc22140"),
                            IsPrivate = false,
                            Number = 44
                        },
                        new
                        {
                            Id = new Guid("5597c585-9739-4688-8977-717cee2ffaee"),
                            IsPrivate = false,
                            Number = 45
                        },
                        new
                        {
                            Id = new Guid("2de3c6f0-0029-4fff-bbff-98fca2ff69fe"),
                            IsPrivate = false,
                            Number = 46
                        },
                        new
                        {
                            Id = new Guid("9c37db0f-7378-41a7-816a-1289dde7c1a8"),
                            IsPrivate = false,
                            Number = 47
                        },
                        new
                        {
                            Id = new Guid("22b12c46-13ff-4e54-9ea8-935d192a779a"),
                            IsPrivate = false,
                            Number = 48
                        },
                        new
                        {
                            Id = new Guid("2e4b9d42-a320-4fde-a96a-770a3d922450"),
                            IsPrivate = false,
                            Number = 49
                        },
                        new
                        {
                            Id = new Guid("53208d55-4c02-4484-bbe7-2588d0c70342"),
                            IsPrivate = false,
                            Number = 50
                        },
                        new
                        {
                            Id = new Guid("96b2e0ac-a9b0-44ea-b3a8-d56b1e0c5e20"),
                            IsPrivate = false,
                            Number = 51
                        },
                        new
                        {
                            Id = new Guid("60a31539-2f1c-4286-b865-6ee0f518c676"),
                            IsPrivate = false,
                            Number = 52
                        },
                        new
                        {
                            Id = new Guid("687efe58-596a-4912-9447-854c6a1e6531"),
                            IsPrivate = false,
                            Number = 53
                        },
                        new
                        {
                            Id = new Guid("fd23cd21-17f8-4c7f-8e44-a029b625f6e5"),
                            IsPrivate = false,
                            Number = 54
                        },
                        new
                        {
                            Id = new Guid("cca85175-69e2-4b32-90a7-40e61020b443"),
                            IsPrivate = false,
                            Number = 55
                        },
                        new
                        {
                            Id = new Guid("c1d7c344-d0d3-4608-a028-b6dfc18be937"),
                            IsPrivate = false,
                            Number = 56
                        },
                        new
                        {
                            Id = new Guid("e9dcd3f8-00ea-4bae-9e6f-6877b9253c42"),
                            IsPrivate = false,
                            Number = 57
                        },
                        new
                        {
                            Id = new Guid("9d5cb23c-245e-47bb-aa94-7da82fb69272"),
                            IsPrivate = false,
                            Number = 58
                        },
                        new
                        {
                            Id = new Guid("2eb426b3-98c4-43b3-896e-9b83dbba5942"),
                            IsPrivate = false,
                            Number = 59
                        },
                        new
                        {
                            Id = new Guid("fd66dbd3-afea-4453-87e1-dd0c33d47436"),
                            IsPrivate = false,
                            Number = 60
                        },
                        new
                        {
                            Id = new Guid("e95308e2-044e-4fab-9192-2b02f9d04d3b"),
                            IsPrivate = false,
                            Number = 61
                        },
                        new
                        {
                            Id = new Guid("1995673f-55b6-4400-947c-05ee4993c250"),
                            IsPrivate = false,
                            Number = 62
                        },
                        new
                        {
                            Id = new Guid("3bca7746-9c81-4f65-91e2-66942a4d6dc9"),
                            IsPrivate = false,
                            Number = 63
                        },
                        new
                        {
                            Id = new Guid("58f9d884-7a96-45ea-840a-d898e82399ca"),
                            IsPrivate = false,
                            Number = 64
                        },
                        new
                        {
                            Id = new Guid("804d9110-3515-420a-afd5-9016fd97604d"),
                            IsPrivate = false,
                            Number = 65
                        },
                        new
                        {
                            Id = new Guid("19c805be-d4d9-491b-8a1f-5c492aada4d6"),
                            IsPrivate = false,
                            Number = 66
                        },
                        new
                        {
                            Id = new Guid("03117af4-9c3c-4f44-b74a-2d16af6d466f"),
                            IsPrivate = false,
                            Number = 67
                        },
                        new
                        {
                            Id = new Guid("00ece840-d553-4275-a14b-8ce8a045d09f"),
                            IsPrivate = false,
                            Number = 68
                        },
                        new
                        {
                            Id = new Guid("fe518e1e-1a97-4ae7-8c5e-6337bc28628a"),
                            IsPrivate = false,
                            Number = 69
                        },
                        new
                        {
                            Id = new Guid("3ba56c00-0ff5-4ed6-88f2-5799f83e8abd"),
                            IsPrivate = false,
                            Number = 70
                        },
                        new
                        {
                            Id = new Guid("d7b6ff1d-dd04-494f-b7d0-cd74838a1ae5"),
                            IsPrivate = false,
                            Number = 71
                        },
                        new
                        {
                            Id = new Guid("f3b8b37d-a54e-4861-b0db-21f0e9e67ed0"),
                            IsPrivate = false,
                            Number = 72
                        },
                        new
                        {
                            Id = new Guid("cd3bc2b8-b9c6-422f-9b14-4e21348af86a"),
                            IsPrivate = false,
                            Number = 73
                        },
                        new
                        {
                            Id = new Guid("18d87ac2-6136-468e-b711-d9062c8b3c50"),
                            IsPrivate = false,
                            Number = 74
                        },
                        new
                        {
                            Id = new Guid("359bfc5a-873e-40d9-b5a1-71eea7a2878e"),
                            IsPrivate = false,
                            Number = 75
                        },
                        new
                        {
                            Id = new Guid("3aca757b-bbfd-43b8-b7a8-7a6a2ded9726"),
                            IsPrivate = false,
                            Number = 76
                        },
                        new
                        {
                            Id = new Guid("3a3168f0-6326-4e84-ba28-1fc8adcb0050"),
                            IsPrivate = false,
                            Number = 77
                        },
                        new
                        {
                            Id = new Guid("578d461d-d52f-4728-b01b-42edc8e54d08"),
                            IsPrivate = false,
                            Number = 78
                        },
                        new
                        {
                            Id = new Guid("6d35fe04-e9ed-48f0-b58e-087a91727a0b"),
                            IsPrivate = false,
                            Number = 79
                        },
                        new
                        {
                            Id = new Guid("706cb711-ec66-4c1b-8293-484bdb8f4c36"),
                            IsPrivate = false,
                            Number = 80
                        },
                        new
                        {
                            Id = new Guid("58dbc897-7928-41c6-99d6-c650cacffd21"),
                            IsPrivate = false,
                            Number = 81
                        },
                        new
                        {
                            Id = new Guid("49b41fac-41bf-4c57-aea7-bcd66f74a70c"),
                            IsPrivate = false,
                            Number = 82
                        },
                        new
                        {
                            Id = new Guid("66d378da-4a40-40ee-9e94-a8cbacb03502"),
                            IsPrivate = false,
                            Number = 83
                        },
                        new
                        {
                            Id = new Guid("5aec764c-3268-4eee-a0fe-46590c04c77c"),
                            IsPrivate = false,
                            Number = 84
                        },
                        new
                        {
                            Id = new Guid("ad856f28-bb5e-4ae4-bbae-a3450c1e3b56"),
                            IsPrivate = false,
                            Number = 85
                        },
                        new
                        {
                            Id = new Guid("217324a3-381b-4aff-a8d4-5ac462c6f4bc"),
                            IsPrivate = false,
                            Number = 86
                        },
                        new
                        {
                            Id = new Guid("d052b62e-51f2-43b7-a859-c175fb27bf86"),
                            IsPrivate = false,
                            Number = 87
                        },
                        new
                        {
                            Id = new Guid("1f161a58-ef38-46da-94db-352fd423fab0"),
                            IsPrivate = false,
                            Number = 88
                        },
                        new
                        {
                            Id = new Guid("17743244-37ff-4a59-89ab-36ed6f70ecb4"),
                            IsPrivate = false,
                            Number = 89
                        },
                        new
                        {
                            Id = new Guid("901ecb55-e08c-43f2-8916-67e5470e7927"),
                            IsPrivate = false,
                            Number = 90
                        },
                        new
                        {
                            Id = new Guid("08f5028a-a98e-48bf-b7f4-c6c96d3d3249"),
                            IsPrivate = false,
                            Number = 91
                        },
                        new
                        {
                            Id = new Guid("76804845-8d08-4f68-9327-62bab73d12c0"),
                            IsPrivate = false,
                            Number = 92
                        },
                        new
                        {
                            Id = new Guid("c72b9070-2f54-4443-9468-31d24872a07c"),
                            IsPrivate = false,
                            Number = 93
                        },
                        new
                        {
                            Id = new Guid("22e23c4e-73a3-48d2-9dac-2d406c1ab5d1"),
                            IsPrivate = false,
                            Number = 94
                        },
                        new
                        {
                            Id = new Guid("adf91b94-1cc2-4c69-8239-a85b73952daa"),
                            IsPrivate = false,
                            Number = 95
                        },
                        new
                        {
                            Id = new Guid("ca332c60-1fe4-4256-a77f-8df4bc0aeb15"),
                            IsPrivate = false,
                            Number = 96
                        },
                        new
                        {
                            Id = new Guid("815acd82-9ec9-4dfd-bdd5-b3c2632ef6e4"),
                            IsPrivate = false,
                            Number = 97
                        },
                        new
                        {
                            Id = new Guid("f7f1946b-e036-414b-bf5c-bb5a8900fc59"),
                            IsPrivate = false,
                            Number = 98
                        },
                        new
                        {
                            Id = new Guid("2e29dd18-3947-4cab-a33d-926cf3a88a93"),
                            IsPrivate = false,
                            Number = 99
                        },
                        new
                        {
                            Id = new Guid("e479d329-47c2-4894-b245-4923bc87d53a"),
                            IsPrivate = false,
                            Number = 100
                        },
                        new
                        {
                            Id = new Guid("e3dc571b-00f1-474f-b6b3-b892b7da0220"),
                            IsPrivate = false,
                            Number = 101
                        },
                        new
                        {
                            Id = new Guid("45695498-4291-40d7-97a8-78b30fe11ff7"),
                            IsPrivate = false,
                            Number = 102
                        },
                        new
                        {
                            Id = new Guid("22e61285-4e8b-4f63-83f9-0f9edec37dcb"),
                            IsPrivate = false,
                            Number = 103
                        },
                        new
                        {
                            Id = new Guid("0511dbdd-2457-4c4a-ae10-3069c1d0d574"),
                            IsPrivate = false,
                            Number = 104
                        },
                        new
                        {
                            Id = new Guid("a06aadf0-a5bb-495a-893c-549eed862e25"),
                            IsPrivate = false,
                            Number = 105
                        },
                        new
                        {
                            Id = new Guid("1fc073dd-3d54-42b3-9531-e74b476d5841"),
                            IsPrivate = false,
                            Number = 106
                        },
                        new
                        {
                            Id = new Guid("31ffaff7-fa08-41d0-90f3-4a6dce8c88d2"),
                            IsPrivate = false,
                            Number = 107
                        },
                        new
                        {
                            Id = new Guid("3c46d4ef-15cb-4495-a68f-251b7b10b65d"),
                            IsPrivate = false,
                            Number = 108
                        },
                        new
                        {
                            Id = new Guid("f1cd5cb6-775d-43c7-adad-91d266d72589"),
                            IsPrivate = false,
                            Number = 109
                        },
                        new
                        {
                            Id = new Guid("8b1bef75-059d-44cd-8745-a664bea62810"),
                            IsPrivate = false,
                            Number = 110
                        },
                        new
                        {
                            Id = new Guid("2e5c82c8-749c-4900-9dd5-4d5f370f8025"),
                            IsPrivate = false,
                            Number = 111
                        },
                        new
                        {
                            Id = new Guid("eef22674-f057-4df9-bda5-1429caeb41e0"),
                            IsPrivate = false,
                            Number = 112
                        },
                        new
                        {
                            Id = new Guid("336876ef-28c1-475f-a386-9df9875df402"),
                            IsPrivate = false,
                            Number = 113
                        },
                        new
                        {
                            Id = new Guid("6a58ffc3-5f8c-4350-8d99-01cfd0ea4279"),
                            IsPrivate = false,
                            Number = 114
                        },
                        new
                        {
                            Id = new Guid("ba289f8a-90a3-4091-b8b4-0271073e38d4"),
                            IsPrivate = false,
                            Number = 115
                        },
                        new
                        {
                            Id = new Guid("c40d68ec-2562-4197-8319-cad76e27843c"),
                            IsPrivate = false,
                            Number = 116
                        },
                        new
                        {
                            Id = new Guid("2bd1cafa-1f44-4edb-8a16-14902e2871c6"),
                            IsPrivate = false,
                            Number = 117
                        },
                        new
                        {
                            Id = new Guid("121a61b0-cc71-43a1-b010-70fd7c806ba1"),
                            IsPrivate = false,
                            Number = 118
                        },
                        new
                        {
                            Id = new Guid("cfb48de2-cd6c-4147-95ad-bd68e01c3efd"),
                            IsPrivate = false,
                            Number = 119
                        },
                        new
                        {
                            Id = new Guid("55e1a1ec-51a7-46d0-a9c8-713047c30e1f"),
                            IsPrivate = false,
                            Number = 120
                        },
                        new
                        {
                            Id = new Guid("6f25ad91-e37f-41f9-8a86-005bede4abdd"),
                            IsPrivate = false,
                            Number = 121
                        },
                        new
                        {
                            Id = new Guid("4ef333b7-6c12-4d9d-831d-9397619e7f93"),
                            IsPrivate = false,
                            Number = 122
                        },
                        new
                        {
                            Id = new Guid("66117c75-7454-48ee-bf8a-8517021dbad6"),
                            IsPrivate = false,
                            Number = 123
                        },
                        new
                        {
                            Id = new Guid("1de09070-5fa3-4856-a6cc-77cfd47b6e5d"),
                            IsPrivate = false,
                            Number = 124
                        },
                        new
                        {
                            Id = new Guid("99e1c0ef-61a4-4303-b61c-f8baaad5ad3e"),
                            IsPrivate = false,
                            Number = 125
                        },
                        new
                        {
                            Id = new Guid("d28228c6-815d-4fdf-aa3f-2770fb190bcc"),
                            IsPrivate = false,
                            Number = 126
                        },
                        new
                        {
                            Id = new Guid("2fab52a3-7eea-4e5c-97e1-2f5bf44b35c9"),
                            IsPrivate = false,
                            Number = 127
                        },
                        new
                        {
                            Id = new Guid("9ba53170-27a9-4994-a847-72d729549fec"),
                            IsPrivate = false,
                            Number = 128
                        },
                        new
                        {
                            Id = new Guid("281700ff-b5f5-466b-9628-0bdfe19ab576"),
                            IsPrivate = false,
                            Number = 129
                        },
                        new
                        {
                            Id = new Guid("a0bea6cd-8720-4948-817d-d463844b5b58"),
                            IsPrivate = false,
                            Number = 130
                        },
                        new
                        {
                            Id = new Guid("122bb481-f69b-4537-8183-fb0bbb559dac"),
                            IsPrivate = false,
                            Number = 131
                        },
                        new
                        {
                            Id = new Guid("38ecb755-9498-4fc7-934a-fde521229880"),
                            IsPrivate = false,
                            Number = 132
                        },
                        new
                        {
                            Id = new Guid("6f7a61e7-40ef-471c-960b-eba12e1abb93"),
                            IsPrivate = false,
                            Number = 133
                        },
                        new
                        {
                            Id = new Guid("de59080a-5f07-4b74-94a1-6c5c1be0277b"),
                            IsPrivate = false,
                            Number = 134
                        },
                        new
                        {
                            Id = new Guid("0293eb59-2010-4a99-80d7-beab0f459e4d"),
                            IsPrivate = false,
                            Number = 135
                        },
                        new
                        {
                            Id = new Guid("5f79f8a5-447b-4dd5-ae8c-96256cdc0e54"),
                            IsPrivate = false,
                            Number = 136
                        },
                        new
                        {
                            Id = new Guid("b0bc7489-d6a8-4966-96eb-f7a08aba7887"),
                            IsPrivate = false,
                            Number = 137
                        },
                        new
                        {
                            Id = new Guid("b8ba1e4b-a343-4e62-bae8-bd60124b30ad"),
                            IsPrivate = false,
                            Number = 138
                        },
                        new
                        {
                            Id = new Guid("9243e39f-01ec-4901-937b-1e6f6fe8389a"),
                            IsPrivate = false,
                            Number = 139
                        },
                        new
                        {
                            Id = new Guid("de928341-ef30-4cf2-b363-e5e10a6cc2ff"),
                            IsPrivate = false,
                            Number = 140
                        },
                        new
                        {
                            Id = new Guid("fe0de21c-de32-4b3b-8c23-c27f2292f3fa"),
                            IsPrivate = false,
                            Number = 141
                        },
                        new
                        {
                            Id = new Guid("7cbded77-db40-47cf-914f-527dfaf3f21f"),
                            IsPrivate = false,
                            Number = 142
                        },
                        new
                        {
                            Id = new Guid("1b97a8e8-a92b-4c00-a45e-b5a358caf7f2"),
                            IsPrivate = false,
                            Number = 143
                        },
                        new
                        {
                            Id = new Guid("bc9211da-4578-420e-b814-6bf04c1196ca"),
                            IsPrivate = false,
                            Number = 144
                        },
                        new
                        {
                            Id = new Guid("3c547304-0e1d-4eaf-96e3-eab5cedc97a6"),
                            IsPrivate = false,
                            Number = 145
                        },
                        new
                        {
                            Id = new Guid("b938223a-3ac1-488a-bec2-cdebe92b8ab3"),
                            IsPrivate = false,
                            Number = 146
                        },
                        new
                        {
                            Id = new Guid("3adc0b8b-0426-4aef-a040-b1c702fc3357"),
                            IsPrivate = false,
                            Number = 147
                        },
                        new
                        {
                            Id = new Guid("733306f5-8be5-4578-bb17-12b483030311"),
                            IsPrivate = false,
                            Number = 148
                        },
                        new
                        {
                            Id = new Guid("8085a014-f86f-44a9-812b-ffad87dc3508"),
                            IsPrivate = false,
                            Number = 149
                        },
                        new
                        {
                            Id = new Guid("a82995fd-f423-434c-8455-346e5caf1776"),
                            IsPrivate = false,
                            Number = 150
                        },
                        new
                        {
                            Id = new Guid("53e31717-0f61-4a21-86fd-c9cf17c09a17"),
                            IsPrivate = false,
                            Number = 151
                        },
                        new
                        {
                            Id = new Guid("60b91e70-5e95-4793-b60a-4d84c5406dd0"),
                            IsPrivate = false,
                            Number = 152
                        },
                        new
                        {
                            Id = new Guid("150b8bf4-0482-46f6-b63b-1344c79816ce"),
                            IsPrivate = false,
                            Number = 153
                        },
                        new
                        {
                            Id = new Guid("1f565121-0ebf-41ab-a1eb-3306f9b24eb2"),
                            IsPrivate = false,
                            Number = 154
                        },
                        new
                        {
                            Id = new Guid("4ea77620-b971-48fa-a231-b148b23cfcfc"),
                            IsPrivate = false,
                            Number = 155
                        },
                        new
                        {
                            Id = new Guid("6a18fae2-a2cf-4b5a-818d-2035b971f6e8"),
                            IsPrivate = false,
                            Number = 156
                        },
                        new
                        {
                            Id = new Guid("af0f25ee-d7d9-4f35-8a99-c0f8c1eed43a"),
                            IsPrivate = false,
                            Number = 157
                        },
                        new
                        {
                            Id = new Guid("c1aea79c-e796-4ce0-9cfb-12a9cfa71503"),
                            IsPrivate = false,
                            Number = 158
                        },
                        new
                        {
                            Id = new Guid("69a3f5bf-54ac-4739-b14b-d9ed8069f2ca"),
                            IsPrivate = false,
                            Number = 159
                        },
                        new
                        {
                            Id = new Guid("d72dd0c4-2b0d-456a-9ff5-2f5565915411"),
                            IsPrivate = false,
                            Number = 160
                        },
                        new
                        {
                            Id = new Guid("392bd608-8634-4de0-b2e9-9ce677c02fe0"),
                            IsPrivate = false,
                            Number = 161
                        },
                        new
                        {
                            Id = new Guid("f36da128-ec85-4d29-b9a1-cca47246556f"),
                            IsPrivate = false,
                            Number = 162
                        },
                        new
                        {
                            Id = new Guid("3ea0493a-d293-4492-b148-9e16e038f619"),
                            IsPrivate = false,
                            Number = 163
                        },
                        new
                        {
                            Id = new Guid("5460f015-1b68-49a0-8333-e8190279ad87"),
                            IsPrivate = false,
                            Number = 164
                        },
                        new
                        {
                            Id = new Guid("82144220-8735-4358-a064-62a2a36ef76b"),
                            IsPrivate = false,
                            Number = 165
                        },
                        new
                        {
                            Id = new Guid("687407e2-5851-437a-9df0-7b179803067f"),
                            IsPrivate = false,
                            Number = 166
                        },
                        new
                        {
                            Id = new Guid("36cf83ff-af49-411c-9637-34893a67d687"),
                            IsPrivate = false,
                            Number = 167
                        },
                        new
                        {
                            Id = new Guid("f229cd84-5e6e-4fa8-bf63-3f8fd66647ae"),
                            IsPrivate = false,
                            Number = 168
                        },
                        new
                        {
                            Id = new Guid("4d1be3bb-04f6-4b41-9a4d-a5c9da36f02a"),
                            IsPrivate = false,
                            Number = 169
                        },
                        new
                        {
                            Id = new Guid("5f10222c-eff1-4c99-be2d-6c3d01152d4c"),
                            IsPrivate = false,
                            Number = 170
                        },
                        new
                        {
                            Id = new Guid("e17479cd-d5c6-4c7f-b31d-808e390ca8c9"),
                            IsPrivate = false,
                            Number = 171
                        },
                        new
                        {
                            Id = new Guid("2fe1117e-b1c9-40f5-b706-d3c583eb22c1"),
                            IsPrivate = false,
                            Number = 172
                        },
                        new
                        {
                            Id = new Guid("c663378b-5d9d-4b04-aa25-3a37b50a7c8e"),
                            IsPrivate = false,
                            Number = 173
                        },
                        new
                        {
                            Id = new Guid("41faf58a-812e-48cd-b695-a8f9c87580c2"),
                            IsPrivate = false,
                            Number = 174
                        },
                        new
                        {
                            Id = new Guid("5ff81a77-76ed-4cc5-9656-bccfee8f4540"),
                            IsPrivate = false,
                            Number = 175
                        },
                        new
                        {
                            Id = new Guid("339ded3f-b97c-48ba-8ccf-bc91c4e2ce4c"),
                            IsPrivate = false,
                            Number = 176
                        },
                        new
                        {
                            Id = new Guid("0b957eb7-32ba-41ac-b9d3-edf7683b6cae"),
                            IsPrivate = false,
                            Number = 177
                        },
                        new
                        {
                            Id = new Guid("d4dc393c-1cdd-410c-b65d-cb0c94a6bdb7"),
                            IsPrivate = false,
                            Number = 178
                        },
                        new
                        {
                            Id = new Guid("e9c23710-27f9-49db-bd0d-5be85cae1d22"),
                            IsPrivate = false,
                            Number = 179
                        },
                        new
                        {
                            Id = new Guid("5f3b78ef-34fd-4b30-b15e-e7e6eb22dcdc"),
                            IsPrivate = false,
                            Number = 180
                        },
                        new
                        {
                            Id = new Guid("a09d6a95-d505-4bde-a6bd-b40ad5989751"),
                            IsPrivate = false,
                            Number = 181
                        },
                        new
                        {
                            Id = new Guid("2d5e52c4-8f63-4c2a-822a-20597fad5745"),
                            IsPrivate = false,
                            Number = 182
                        },
                        new
                        {
                            Id = new Guid("78593e67-eae9-4092-94fb-b75dcc96f3ff"),
                            IsPrivate = false,
                            Number = 183
                        },
                        new
                        {
                            Id = new Guid("c89eea29-de8b-42df-920f-9226d5b4e976"),
                            IsPrivate = false,
                            Number = 184
                        },
                        new
                        {
                            Id = new Guid("660b481b-1ec5-4f58-8251-c7fa631c7c3b"),
                            IsPrivate = false,
                            Number = 185
                        },
                        new
                        {
                            Id = new Guid("f7673a72-725f-4ab2-aee0-0314ae394768"),
                            IsPrivate = false,
                            Number = 186
                        },
                        new
                        {
                            Id = new Guid("d5a5287b-475b-488b-8b73-2b8b056d9873"),
                            IsPrivate = false,
                            Number = 187
                        },
                        new
                        {
                            Id = new Guid("483da1cb-d9c7-49c9-8af4-82279a030f7b"),
                            IsPrivate = false,
                            Number = 188
                        },
                        new
                        {
                            Id = new Guid("d9dae992-e406-4da7-bad8-5f168d57a806"),
                            IsPrivate = false,
                            Number = 189
                        },
                        new
                        {
                            Id = new Guid("826c6130-20bd-40e0-9ac8-fd9dc3eb07b2"),
                            IsPrivate = false,
                            Number = 190
                        },
                        new
                        {
                            Id = new Guid("c723ec37-ff52-43ff-aea8-ab98b4ccbee0"),
                            IsPrivate = false,
                            Number = 191
                        },
                        new
                        {
                            Id = new Guid("2f691298-2abf-4e7c-bc3f-5c5150e1377d"),
                            IsPrivate = false,
                            Number = 192
                        },
                        new
                        {
                            Id = new Guid("bd15b61f-1d79-451c-9445-d151132376bd"),
                            IsPrivate = false,
                            Number = 193
                        },
                        new
                        {
                            Id = new Guid("576baf57-81ac-41c1-a1c6-7e5f2ee45449"),
                            IsPrivate = false,
                            Number = 194
                        },
                        new
                        {
                            Id = new Guid("3805e176-ed10-4294-949b-056f17a0963e"),
                            IsPrivate = false,
                            Number = 195
                        },
                        new
                        {
                            Id = new Guid("bb5923e6-561f-4ac7-8785-2280433f2b17"),
                            IsPrivate = false,
                            Number = 196
                        },
                        new
                        {
                            Id = new Guid("6ea60eee-662e-4d2e-ac43-2d125d856751"),
                            IsPrivate = false,
                            Number = 197
                        },
                        new
                        {
                            Id = new Guid("fcb3400f-7aa7-4d9e-870a-fe610879cd94"),
                            IsPrivate = false,
                            Number = 198
                        },
                        new
                        {
                            Id = new Guid("bb4313b9-0c0d-4ac4-8d63-43dd447e7440"),
                            IsPrivate = false,
                            Number = 199
                        },
                        new
                        {
                            Id = new Guid("2dc2a749-9c34-4f9d-a7c0-e9408f3e4f17"),
                            IsPrivate = false,
                            Number = 200
                        },
                        new
                        {
                            Id = new Guid("53629da1-930f-4aa5-b7b0-38c79588f7cf"),
                            IsPrivate = false,
                            Number = 201
                        },
                        new
                        {
                            Id = new Guid("b57e9a75-2108-4bb9-8a15-c3adfe46c4cd"),
                            IsPrivate = false,
                            Number = 202
                        },
                        new
                        {
                            Id = new Guid("135d7e53-e44a-4488-b007-7102f1dcd841"),
                            IsPrivate = false,
                            Number = 203
                        },
                        new
                        {
                            Id = new Guid("6bf8d769-704e-4cd0-a73a-4417166be70f"),
                            IsPrivate = false,
                            Number = 204
                        },
                        new
                        {
                            Id = new Guid("8e042487-1d5c-4f86-ba48-3e88d0590356"),
                            IsPrivate = false,
                            Number = 205
                        },
                        new
                        {
                            Id = new Guid("bfc2966e-f5ae-48f1-8e2d-4a5e0dfbade1"),
                            IsPrivate = false,
                            Number = 206
                        },
                        new
                        {
                            Id = new Guid("cb1f50e3-b523-4661-9068-bc981ca21186"),
                            IsPrivate = false,
                            Number = 207
                        },
                        new
                        {
                            Id = new Guid("a2be18c3-5368-4257-b659-c7b26e5543b5"),
                            IsPrivate = false,
                            Number = 208
                        },
                        new
                        {
                            Id = new Guid("62689cca-9dfb-4cca-b690-c3fdbf8c3cea"),
                            IsPrivate = false,
                            Number = 209
                        },
                        new
                        {
                            Id = new Guid("fd0468e1-1ff4-4130-b850-d09d749cd549"),
                            IsPrivate = false,
                            Number = 210
                        },
                        new
                        {
                            Id = new Guid("bd39244f-ae03-4827-830f-f634ba8edd37"),
                            IsPrivate = false,
                            Number = 211
                        },
                        new
                        {
                            Id = new Guid("13787d26-27f0-4765-978e-bdb39dbba759"),
                            IsPrivate = false,
                            Number = 212
                        },
                        new
                        {
                            Id = new Guid("da87991a-3a54-4003-887f-9168f0904a1a"),
                            IsPrivate = false,
                            Number = 213
                        },
                        new
                        {
                            Id = new Guid("2d030cbc-9f4d-4ea0-add2-93e7213a0d25"),
                            IsPrivate = false,
                            Number = 214
                        },
                        new
                        {
                            Id = new Guid("8015ee40-4fcb-4351-89f5-db47ff719f62"),
                            IsPrivate = false,
                            Number = 215
                        },
                        new
                        {
                            Id = new Guid("6771c2b7-c6b6-46c4-82a7-6e08a3c748de"),
                            IsPrivate = false,
                            Number = 216
                        },
                        new
                        {
                            Id = new Guid("00d67071-270b-4a5c-8b55-ce08e9025634"),
                            IsPrivate = false,
                            Number = 217
                        },
                        new
                        {
                            Id = new Guid("624fd2a1-5b7f-4f28-9326-a0911dec41ea"),
                            IsPrivate = false,
                            Number = 218
                        },
                        new
                        {
                            Id = new Guid("d3440a03-db62-42f9-bad1-fe3d192fcf66"),
                            IsPrivate = false,
                            Number = 219
                        },
                        new
                        {
                            Id = new Guid("57415330-8fdd-4722-8ae9-b39b544dd84e"),
                            IsPrivate = false,
                            Number = 220
                        },
                        new
                        {
                            Id = new Guid("d3bf52b6-2e11-4e25-ba52-8b782e4e650c"),
                            IsPrivate = false,
                            Number = 221
                        },
                        new
                        {
                            Id = new Guid("705c5484-b044-4629-8c95-506f29c92b6c"),
                            IsPrivate = false,
                            Number = 222
                        },
                        new
                        {
                            Id = new Guid("3d2f4036-0e7b-4f92-b8e2-a4955e1a61f3"),
                            IsPrivate = false,
                            Number = 223
                        },
                        new
                        {
                            Id = new Guid("11640d9c-3021-40fd-8d9b-cd9290b2f4a5"),
                            IsPrivate = false,
                            Number = 224
                        },
                        new
                        {
                            Id = new Guid("90cf0c3a-6730-4ee0-b939-43578acedf8b"),
                            IsPrivate = false,
                            Number = 225
                        },
                        new
                        {
                            Id = new Guid("5c8885ce-3799-4270-9eb7-f5dc69de8bac"),
                            IsPrivate = false,
                            Number = 226
                        },
                        new
                        {
                            Id = new Guid("5ddcae1f-eb48-4393-a5a4-014a1b4df561"),
                            IsPrivate = false,
                            Number = 227
                        },
                        new
                        {
                            Id = new Guid("e0bc37e6-4d38-46a6-a710-cbdfa7d8ec29"),
                            IsPrivate = false,
                            Number = 228
                        },
                        new
                        {
                            Id = new Guid("763321e2-18c9-4ff1-adaa-feb914240b2f"),
                            IsPrivate = false,
                            Number = 229
                        },
                        new
                        {
                            Id = new Guid("41e22eef-d1fe-4e9a-b3b6-70588dc3f3f7"),
                            IsPrivate = false,
                            Number = 230
                        },
                        new
                        {
                            Id = new Guid("8d16f973-8357-41f3-b99c-41037cb9892f"),
                            IsPrivate = false,
                            Number = 231
                        },
                        new
                        {
                            Id = new Guid("5cb819d1-df98-4993-9b40-5d71f8c48766"),
                            IsPrivate = false,
                            Number = 232
                        },
                        new
                        {
                            Id = new Guid("e15b5487-480b-4131-a4cd-5f443480e58a"),
                            IsPrivate = false,
                            Number = 233
                        },
                        new
                        {
                            Id = new Guid("6203a49b-9cc2-43fa-8486-d41d627b9828"),
                            IsPrivate = false,
                            Number = 234
                        },
                        new
                        {
                            Id = new Guid("d498018a-f69a-4d68-a271-9db7f9f0c56c"),
                            IsPrivate = false,
                            Number = 235
                        },
                        new
                        {
                            Id = new Guid("0cf14cc9-531d-41a2-9163-146a748be8eb"),
                            IsPrivate = false,
                            Number = 236
                        },
                        new
                        {
                            Id = new Guid("203c2ab2-59e7-4a7f-99cc-7978ccc1cf7b"),
                            IsPrivate = false,
                            Number = 237
                        },
                        new
                        {
                            Id = new Guid("068348cc-3ec3-49ff-9fd2-1b70b5a2bf52"),
                            IsPrivate = false,
                            Number = 238
                        },
                        new
                        {
                            Id = new Guid("cb00b0ba-2474-4465-bc4e-e8af2b78d203"),
                            IsPrivate = false,
                            Number = 239
                        },
                        new
                        {
                            Id = new Guid("34ba3af2-c74d-47b9-a69c-e08bd98d3231"),
                            IsPrivate = false,
                            Number = 240
                        },
                        new
                        {
                            Id = new Guid("cd1eb309-4567-44eb-9049-16c9aeb287af"),
                            IsPrivate = false,
                            Number = 241
                        },
                        new
                        {
                            Id = new Guid("25e36d98-2f8f-4553-84e7-c5b497c2dc32"),
                            IsPrivate = false,
                            Number = 242
                        },
                        new
                        {
                            Id = new Guid("dec8270d-cb4d-43da-a686-8bfdbf32310c"),
                            IsPrivate = false,
                            Number = 243
                        },
                        new
                        {
                            Id = new Guid("cfcc6b0b-7a4b-440e-944b-1c0630d1668c"),
                            IsPrivate = false,
                            Number = 244
                        },
                        new
                        {
                            Id = new Guid("d813368a-ecc0-4df9-88e0-11c3ab5c1dc3"),
                            IsPrivate = false,
                            Number = 245
                        },
                        new
                        {
                            Id = new Guid("9b91557d-ca70-466d-b276-c53cf7a2415d"),
                            IsPrivate = false,
                            Number = 246
                        },
                        new
                        {
                            Id = new Guid("8f1ee1f5-176e-4ed3-a51b-68c88436207d"),
                            IsPrivate = false,
                            Number = 247
                        },
                        new
                        {
                            Id = new Guid("5c5e00ea-4573-4bd5-a46e-62c0b5120944"),
                            IsPrivate = false,
                            Number = 248
                        },
                        new
                        {
                            Id = new Guid("ff05ac91-138c-4011-805c-4d9863ac1192"),
                            IsPrivate = false,
                            Number = 249
                        },
                        new
                        {
                            Id = new Guid("069720dd-a77c-48cd-8d58-ad825b69a349"),
                            IsPrivate = false,
                            Number = 250
                        },
                        new
                        {
                            Id = new Guid("936ecd8f-7d40-4159-b17b-f24319770b7e"),
                            IsPrivate = false,
                            Number = 251
                        },
                        new
                        {
                            Id = new Guid("c85d6579-c8f1-4aa6-a832-c3578415a1be"),
                            IsPrivate = false,
                            Number = 252
                        },
                        new
                        {
                            Id = new Guid("e8e47da7-b5e7-421c-b914-062842049d35"),
                            IsPrivate = false,
                            Number = 253
                        },
                        new
                        {
                            Id = new Guid("14c28ce6-9bfa-4cb8-8317-5f59c92ed4d1"),
                            IsPrivate = false,
                            Number = 254
                        },
                        new
                        {
                            Id = new Guid("52ca4c3f-48b1-427b-bb67-5af99e9b229d"),
                            IsPrivate = false,
                            Number = 255
                        },
                        new
                        {
                            Id = new Guid("9e9071ec-4f8d-49a4-aa70-803c07dc6e4f"),
                            IsPrivate = false,
                            Number = 256
                        },
                        new
                        {
                            Id = new Guid("fe6c6c1f-ebd0-4a4f-a8b7-313d202d21d8"),
                            IsPrivate = false,
                            Number = 257
                        },
                        new
                        {
                            Id = new Guid("d328f568-69c4-4296-b214-0166fa8c3b8d"),
                            IsPrivate = false,
                            Number = 258
                        },
                        new
                        {
                            Id = new Guid("49aa9122-cd20-423e-b886-8feb2519ced7"),
                            IsPrivate = false,
                            Number = 259
                        },
                        new
                        {
                            Id = new Guid("89cd4d3d-7e50-49eb-a0f5-2415daf232d8"),
                            IsPrivate = false,
                            Number = 260
                        },
                        new
                        {
                            Id = new Guid("daa2ceee-c563-4ef5-96d6-838ce0754f5a"),
                            IsPrivate = false,
                            Number = 261
                        },
                        new
                        {
                            Id = new Guid("59198d15-6fc0-4ad9-8682-69ee20603333"),
                            IsPrivate = false,
                            Number = 262
                        },
                        new
                        {
                            Id = new Guid("a1d1163e-53a1-4e4b-bb3d-363adfbe840e"),
                            IsPrivate = false,
                            Number = 263
                        },
                        new
                        {
                            Id = new Guid("4ee8c866-b3d0-43ec-b8be-c1292314aee4"),
                            IsPrivate = false,
                            Number = 264
                        },
                        new
                        {
                            Id = new Guid("50c9d0cf-eeef-48c5-9d0e-51b1b435cb2f"),
                            IsPrivate = false,
                            Number = 265
                        },
                        new
                        {
                            Id = new Guid("a14a0957-af6a-4247-82d1-30c863680e0d"),
                            IsPrivate = false,
                            Number = 266
                        },
                        new
                        {
                            Id = new Guid("171dec3e-df01-4029-8751-577524ea14ee"),
                            IsPrivate = false,
                            Number = 267
                        },
                        new
                        {
                            Id = new Guid("f783eb8d-5e1d-4592-9bb4-ae46209d49a6"),
                            IsPrivate = false,
                            Number = 268
                        },
                        new
                        {
                            Id = new Guid("8b7786f6-6433-44cd-a84f-c0b852ef30b9"),
                            IsPrivate = false,
                            Number = 269
                        },
                        new
                        {
                            Id = new Guid("fa3b265b-3fbe-4d89-ad65-2ff861027720"),
                            IsPrivate = false,
                            Number = 270
                        },
                        new
                        {
                            Id = new Guid("66d83018-c5dc-4381-9fc4-e54df3c14d19"),
                            IsPrivate = false,
                            Number = 271
                        },
                        new
                        {
                            Id = new Guid("942c0a9a-28ca-485f-9168-9fc2599238f1"),
                            IsPrivate = false,
                            Number = 272
                        },
                        new
                        {
                            Id = new Guid("28046aed-47d8-44f7-a948-b61276199acb"),
                            IsPrivate = false,
                            Number = 273
                        },
                        new
                        {
                            Id = new Guid("55b378c0-e9d5-4b20-bdbc-c15af9e86471"),
                            IsPrivate = false,
                            Number = 274
                        },
                        new
                        {
                            Id = new Guid("833e2e2d-6626-4ea2-8998-7fcf481e49fd"),
                            IsPrivate = false,
                            Number = 275
                        },
                        new
                        {
                            Id = new Guid("8b953087-fde2-4cb1-9d21-1f35dec40a3a"),
                            IsPrivate = false,
                            Number = 276
                        },
                        new
                        {
                            Id = new Guid("65db3d41-1e0f-48d2-9652-808e39973c4e"),
                            IsPrivate = false,
                            Number = 277
                        },
                        new
                        {
                            Id = new Guid("0649ec54-026a-46e7-84b8-189ff55fd5dd"),
                            IsPrivate = false,
                            Number = 278
                        },
                        new
                        {
                            Id = new Guid("98b1c889-b837-48c1-9f0e-548659023d1b"),
                            IsPrivate = false,
                            Number = 279
                        },
                        new
                        {
                            Id = new Guid("b4d1d432-f576-40c9-98a8-97cd1f7134fd"),
                            IsPrivate = false,
                            Number = 280
                        },
                        new
                        {
                            Id = new Guid("a4267f20-c494-4c05-bfb5-fd8d8e256198"),
                            IsPrivate = false,
                            Number = 281
                        },
                        new
                        {
                            Id = new Guid("3eae48f9-ccb0-41b1-b9ba-dcca8a23802c"),
                            IsPrivate = false,
                            Number = 282
                        },
                        new
                        {
                            Id = new Guid("205878ae-d995-45a0-a7d6-0bd1ee4f4685"),
                            IsPrivate = false,
                            Number = 283
                        },
                        new
                        {
                            Id = new Guid("911f68b7-38f7-499c-a411-a90e9e94a82b"),
                            IsPrivate = false,
                            Number = 284
                        },
                        new
                        {
                            Id = new Guid("248a9a50-6146-483f-9ddf-eeed4f515808"),
                            IsPrivate = false,
                            Number = 285
                        },
                        new
                        {
                            Id = new Guid("fc03c623-eddc-4619-8201-e2f35de4c56a"),
                            IsPrivate = false,
                            Number = 286
                        },
                        new
                        {
                            Id = new Guid("b87f9acb-cc1f-45de-b713-191e4a708a94"),
                            IsPrivate = false,
                            Number = 287
                        },
                        new
                        {
                            Id = new Guid("e70b0017-2747-4d74-98ab-b8c8538c8fd7"),
                            IsPrivate = false,
                            Number = 288
                        },
                        new
                        {
                            Id = new Guid("cbf0c519-a34e-45d1-95e7-62fdf8cd6e87"),
                            IsPrivate = false,
                            Number = 289
                        },
                        new
                        {
                            Id = new Guid("e89112b1-94ec-4902-9502-495c2f3b9d01"),
                            IsPrivate = false,
                            Number = 290
                        },
                        new
                        {
                            Id = new Guid("76e07b8b-fb24-4686-9abd-f6883a84281e"),
                            IsPrivate = false,
                            Number = 291
                        },
                        new
                        {
                            Id = new Guid("02b7d8aa-dc82-46bd-b64f-55f70247600a"),
                            IsPrivate = false,
                            Number = 292
                        },
                        new
                        {
                            Id = new Guid("39c0de83-0b51-48f9-adcc-c2c9b4f5e9d8"),
                            IsPrivate = false,
                            Number = 293
                        },
                        new
                        {
                            Id = new Guid("af8d3eb4-0dda-47f9-b47f-38f6dcd4a7dc"),
                            IsPrivate = false,
                            Number = 294
                        },
                        new
                        {
                            Id = new Guid("37a40914-9370-4ac9-bf34-c0b3b1d9d7ea"),
                            IsPrivate = false,
                            Number = 295
                        },
                        new
                        {
                            Id = new Guid("03f8bd05-bbb3-427e-8370-966ea56d7603"),
                            IsPrivate = false,
                            Number = 296
                        },
                        new
                        {
                            Id = new Guid("084bb095-21a8-4068-a72f-aac0e5334885"),
                            IsPrivate = false,
                            Number = 297
                        },
                        new
                        {
                            Id = new Guid("94cacc0f-0e2c-4fd8-8efa-ba498f05e2aa"),
                            IsPrivate = false,
                            Number = 298
                        },
                        new
                        {
                            Id = new Guid("a1a8e340-70b7-4596-8d50-f34143ab02dc"),
                            IsPrivate = false,
                            Number = 299
                        },
                        new
                        {
                            Id = new Guid("ac211807-9d0b-461d-944e-2d0dfd79e91f"),
                            IsPrivate = false,
                            Number = 300
                        },
                        new
                        {
                            Id = new Guid("29428b53-4423-4e1b-9a89-3ebd9a3d1fd3"),
                            IsPrivate = false,
                            Number = 301
                        },
                        new
                        {
                            Id = new Guid("005c4f2a-d2a1-4a96-8238-6d2d37fb656b"),
                            IsPrivate = false,
                            Number = 302
                        },
                        new
                        {
                            Id = new Guid("6c422ba7-9e00-4b8d-ac31-13889f8ebc1a"),
                            IsPrivate = false,
                            Number = 303
                        },
                        new
                        {
                            Id = new Guid("984faf5e-fb0e-42b6-9bda-25adc3066ef1"),
                            IsPrivate = false,
                            Number = 304
                        },
                        new
                        {
                            Id = new Guid("600c3be4-d548-463f-b30e-4d32871d9dfd"),
                            IsPrivate = false,
                            Number = 305
                        },
                        new
                        {
                            Id = new Guid("916de295-7fec-49ac-8f0f-dfecef967e87"),
                            IsPrivate = false,
                            Number = 306
                        },
                        new
                        {
                            Id = new Guid("f3971ef9-c247-475c-b229-dd4a53ef6f28"),
                            IsPrivate = false,
                            Number = 307
                        },
                        new
                        {
                            Id = new Guid("758ee72e-66b6-4544-98d1-a9ec43363029"),
                            IsPrivate = false,
                            Number = 308
                        },
                        new
                        {
                            Id = new Guid("686e15ab-3dae-424c-b3d3-fe7935913601"),
                            IsPrivate = false,
                            Number = 309
                        },
                        new
                        {
                            Id = new Guid("ad3f3aa1-d319-4895-a6d4-7454e7d83a82"),
                            IsPrivate = false,
                            Number = 310
                        },
                        new
                        {
                            Id = new Guid("86f6cf42-59ee-49f1-938f-768b64b0ffcf"),
                            IsPrivate = false,
                            Number = 311
                        },
                        new
                        {
                            Id = new Guid("94f28082-7e0d-4738-9e13-1f7aac75bc33"),
                            IsPrivate = false,
                            Number = 312
                        },
                        new
                        {
                            Id = new Guid("e51500a0-0c0b-4458-905b-de74e8e46868"),
                            IsPrivate = false,
                            Number = 313
                        },
                        new
                        {
                            Id = new Guid("c9826d3d-10f9-4f9c-a70d-2a42ef2dba26"),
                            IsPrivate = false,
                            Number = 314
                        },
                        new
                        {
                            Id = new Guid("85d1f995-9905-4df7-9014-5c25045ab391"),
                            IsPrivate = false,
                            Number = 315
                        },
                        new
                        {
                            Id = new Guid("810e3d55-dd5e-46fa-8c29-06d5fb337b6e"),
                            IsPrivate = false,
                            Number = 316
                        },
                        new
                        {
                            Id = new Guid("4f6f322e-abf3-49ac-9a68-da08052d1235"),
                            IsPrivate = false,
                            Number = 317
                        },
                        new
                        {
                            Id = new Guid("69d269a8-c423-4efa-8505-d3ac96bbea72"),
                            IsPrivate = false,
                            Number = 318
                        },
                        new
                        {
                            Id = new Guid("1feb3c4d-6275-45c6-8d75-b55cdae154f5"),
                            IsPrivate = false,
                            Number = 319
                        });
                });

            modelBuilder.Entity("GardenCommunityAccounting.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCommunityMember")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("GardenCommunityAccounting.Models.Land", b =>
                {
                    b.HasOne("GardenCommunityAccounting.Models.Person", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");
                });
#pragma warning restore 612, 618
        }
    }
}
